base = float(input("Ingrese la base del rectangulo: "))
altura = float(input("Ingrese la altura del rectangulo: "))

print("Area del rectangulo")
print("base * altura =", base * altura)
print("Perimetro del rectangulo")
print("2 * (base + altura) =", 2 * (base + altura))
print("Diagonal aproximada")
print("(base**2 + altura**2) ** 0.5 =", (base**2 + altura**2) ** 0.5)
print("Mitad del area - triangulo")
print("(base * altura) / 2 =", (base * altura) / 2)
print("Resto division base / altura")
print("base % altura =", base % altura)
print("Base al cuadrado")
print("base ** 2 =", base ** 2)
