print("Operadores de comparacion")
puntaje_a = float(input("Ingrese el puntaje del jugador A: "))
puntaje_b = float(input("Ingrese el puntaje del jugador B: "))
print("Igual a")
print(puntaje_a, "==", puntaje_b, "=", puntaje_a == puntaje_b)
print("Distinto de")
print(puntaje_a, "!=", puntaje_b, "=", puntaje_a != puntaje_b)
print("Menor que")
print(puntaje_a, "<", puntaje_b, "=", puntaje_a < puntaje_b)
print("Mayor que")
print(puntaje_a, ">", puntaje_b, "=", puntaje_a > puntaje_b)
print("Menor o igual que")
print(puntaje_a, "<=", puntaje_b, "=", puntaje_a <= puntaje_b)
print("Mayor o igual que")
print(puntaje_a, ">=", puntaje_b, "=", puntaje_a >= puntaje_b)
