print("Operadores de comparación")
numero1= float(input("Ingrese un numero: "))
numero2= float(input("Ingrese otro numero: "))
print("Igual a")
print(numero1, "==", numero2, "=", numero1 == numero2 )
print("Distinto de")
print(numero1, "!=", numero2, "=", numero1 != numero2 )
print("Menor que")
print(numero1, "<", numero2, "=", numero1 < numero2 )
print("Mayor que")
print(numero1, ">", numero2, "=", numero1 > numero2 )
print("Menor o igual que")
print(numero1, "<=", numero2, "=", numero1 <= numero2 )
print("Mayor o igual que")
print(numero1, ">=", numero2, "=", numero1 >= numero2 )